### ISSUE TITLE
IE animateCenterZoom issue

### ISSUE THREAD

**Issue by jhpoosthoek** [cutting-room-floor/wax#103]
Hi,

I'm trying to use the modest maps animateCenterZoom function (https://github.com/stamen/modestmaps-js/tree/master/examples/zoompan) within wax:
http://jsfiddle.net/63ejb/1/

This works in Chrome/FF/Safari but doesn't work in Internet Explorer (I have IE9). Anyone an idea?

Thanks, Jelmer

**Comment by tmcw** [comment]
That code isn't written to work in IE9 or any version of IE; it relies on getFrame. Code within `examples/` in Modest Maps is known to be experimental; it's outside of `modestmaps.js` for that reason. [Easey](https://github.com/mapbox/easey) contains an IE-compatible version of many of the same features.

**Comment by jhpoosthoek** [comment]
The mm zoompan example on https://github.com/stamen/modestmaps-js/tree/master/examples/zoompan works with IE9, but when I try to use it with wax (e.g. http://jsfiddle.net/63ejb/1/) it doesn't...

Thanks, I'll check out Easey

**Comment by tmcw** [comment]
Closing; post on the trackers Modest Maps / Easey for any questions there
