### ISSUE TITLE
Get data from interaction.

### ISSUE THREAD

**Issue by JonnyBGod** [cutting-room-floor/wax#107]
Hi,

couldn't find conclusive information for this matter anywhere, please forgive me if this as been discussed and point me to it.

The thing is that I need access to the json data when hovering and clicking an area.

Currently I am exploring this with wax over google maps api v3.

Ideally I need to trigger a js function when I click or hover passing it information from the grid.json table.

Thank you in advanced.
Joao

**Comment by tmcw** [comment]
You can use the [callbacks attribute of the options parameter](http://mapbox.github.com/wax/interaction-g.html) to pass an object that has the same methods as a [tooltip object](https://github.com/mapbox/wax/blob/master/control/lib/tooltip.js).
