### ISSUE TITLE
Showing tooltip along mouse pointer

### ISSUE THREAD

**Issue by ghost** [cutting-room-floor/wax#108]
See example using a modified wax.ol.js:
http://s3-eu-west-1.amazonaws.com/nrktest/api/0.3/map.html?basemap=valgomat-2011-kommunesammenslaaing&extent=norway

I've added this code on line 1096:

```
var tooltip = this.callbacks._currentTooltip;
if (tooltip){

  // Default offset is bottom right
  var offsetX = 20;
  var offsetY = 20;

  // Check if horizontal space
  if ((pos.x + tooltip.offsetWidth + offsetX + 5) > this.map.size.w) {
    offsetX = -tooltip.offsetWidth - 5;
  }

  // Check if vertical space
  if ((pos.y + tooltip.offsetHeight + offsetY + 5) > this.map.size.h) {
    offsetY = -35;
  }

  tooltip.style.left = pos.x + offsetX + 'px';
  tooltip.style.top = pos.y + offsetY + 'px';
}
```

What about including a config option telling if the tooltip should follow the mouse pointer or not?

**Comment by tmcw** [comment]
I'm open to pointing to alternative `wax.tooltip` implementations, that do things like following the mouse or anchoring to features on click. I don't want the current implementation to expand any more or gain any more configuration: it's a pluggable control: you can set `callbacks: wax.alttooltip()` and get different behavior in a cleaner way.

**Comment by ghost** [comment]
I've added the code above to the "getInfoForHover" method in "wax.ol.Interaction", and not "wax.tooltip". If I create my own "wax.alttooltip", how can I retrieve information about mouse position and map size without changing "wax.ol.Interaction"?

**Comment by tmcw** [comment]
Your tooltip handler receives the mouse event that creates tooltips. For instance, for a theoretical alternative tooltip called toolbit,

```
toolbit.prototype.over = function(feature, context, evt) {
```

The last parameter is the MouseEvent, which gives you position data. Beyond that, your tooltip library can just subscribe to mousemoves to reposition the tooltip as necessary.

**Comment by turban** [comment]
evt is not available. You need to add it in line 1109 in wax.ol.js:

that.callbacks.over(feature, tiles[t].layer.map.div, evt);
