### ISSUE TITLE
wax.ol.js bug in IE 7 & 8

### ISSUE THREAD

**Issue by ghost** [cutting-room-floor/wax#109]
I'm getting this bug in IE 7 & 8 using wax.ol.js:

Line: 1034
Char: 17
Error: 'tiles[...].frame' is null or not an object

Map: http://s3-eu-west-1.amazonaws.com/nrktest/api/0.3/map-wax.html?basemap=valgomat-2011-kommunesammenslaaing&extent=norway

The error occur is the getInfoForClick even if I'm not clicking on any feature. It seems that IE 7 & 8 is dispatching an click event not occurring in other browsers. 

So far I fixed the issue by removing these lines of code in the setMap function starting on line 940 (as I'm only showing tooltip on mousover): 

```
       // this.clickHandler = new OpenLayers.Handler.Click(
       //     this, {
       //         click: this.getInfoForClick
       //     }
       // );
       // this.clickHandler.setMap(map);
       // this.clickHandler.activate();
```

Map: http://127.0.0.1:8020/NRK%20Dropbox/kart/nrk.Map/api/0.3/map.html?basemap=google_road&extent=norway&overlay=valgomat-2011-kommunesammenslaaing

How to solve this issue without disabling the click handler?

**Comment by tmcw** [comment]
This is a OpenLayers version issue, that otherwise the interaction control accounts for. I'll circle around and finish that compatibility work. In the future, Wax will probably only support the most recent version of OpenLayers, because the project fails to document API breakage at all.

**Comment by tmcw** [comment]
Hey,

Try updating to the very newest dist of wax.ol.js, like https://raw.github.com/mapbox/wax/master/dist/wax.ol.js

I haven't really tested this update, because using OpenLayers makes me black out from rage. So let me know if it works for you.
