### ISSUE TITLE
Build of current wax.leaf is broken?

### ISSUE THREAD

**Issue by onyxfish** [cutting-room-floor/wax#118]
Current leaflet wax kicks out javascript errors about wax.leaf being undefined. On examination it seems that the code that instantiates wax.leaf...

wax.leaf = wax.leaf || {};

...is after the definition of wax.leaf.iteraction.  By moving this to the top of the file I was able to get a working build.

**Comment by tmcw** [comment]
Sorry about that, fixed in a new build. Realized recently that the OpenLayers & Leaflet controls were lagging behind the rest, so I've been hacking on them a bit but don't have good enough test fixtures yet.

**Comment by onyxfish** [comment]
No worries, thanks for the quick fix!
