### ISSUE TITLE
Expose API objects after they are created by wax record

### ISSUE THREAD

**Issue by willwhite** [cutting-room-floor/wax#12]
It would be useful to the expose the actual API objects that the wax record creates so you can use a more traditional API for further manipulation after the wax is processed.

This would allow you to use a wax record as a starting point, but then follow traditional documentation to add further functionality.

**Comment by tmcw** [comment]
wax.Record does return the last thing that it's working on as its return value. In the case of traditional OpenLayers code, this is the OpenLayers.Map object.

**Comment by tmcw** [comment]
The last record is going to be it - there's no real possibility of returning more. I've documented this in the manual along with the guiding philosophy.
