### ISSUE TITLE
Adding a distance scale

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/wax#129]
Moved from https://github.com/mapbox/tilemill/issues/826 by @skorasaurus

I've been interested in adding a distance scale to my maps and noticed this was also mentioned by http://support.mapbox.com/discussions/tilemill/184-map-scales another user. I see that Tom mentioned it's been thought about but I'd like to make this issue just to formalize it if it hasn't already been.

Although it would only support one zoom level, I suppose I could work around this by exporting my stylesheet to mapnik and then adding a scale in mapnik ?

**Comment by skorasaurus** [comment]
Although TileMill is not intended to be a general-purpose cartography tool, but rather focuses on streamlining and simplifying a narrow set of use cases.' I would like to see a distance scale as option for a multi-zoom interactive online map and for single-zoom level exports [PNG/SVG/PDF]

**Comment by tmcw** [comment]
Okay; the two would have to be radically different - one living in Wax and the other requiring improvements to Mapnik's SVG support and a better to-print layer in TileMill. As far as the second use case, that might end up living in a separate tool that specifically does print-output-type-tasks.

**Comment by tmcw** [comment]
Okay: I don't think that this should be done in Wax. If you'd like to implement it yourself, go ahead - or if you want to use [Wax with OpenLayers](http://mapbox.com/wax/connector-ol.html) and use a OpenLayers scale bar, that also works. But scale bars in spherical mercator are mainly misleading, especially in OL's implementation, and not incredibly useful, because they describe only a tiny part of the map surface in large windows.

As far as the output tool, that remains to be seen - it'd be quite an undertaking, and not something that we could easily develop, because we don't really do print output often. We'll see, but closing this ticket for now.
