### ISSUE TITLE
base64-encoded images not showing in the tooltip

### ISSUE THREAD

**Issue by misterboo** [cutting-room-floor/wax#130]
i opened it at tilemill but i guess it is a wax problem

https://github.com/mapbox/tilemill/issues/858

issue is since 3.0.8 , 3.0.7 ist ok

**Comment by misterboo** [comment]
Update: is was the nasty chrome browser cache where the max master was still in.

so 3.0.8 works. The issue seems only the the latest wax master

**Comment by tmcw** [comment]
Fixed in 4.x.x
