### ISSUE TITLE
google maps interaction does not support cursor changes

### ISSUE THREAD

**Issue by underbluewaters** [cutting-room-floor/wax#134]
I've got some interactive tiles visible (2 layers actually), and the cursor does not change to a pointer when showing a tooltip for an intersected feature.  Interactivity works fine otherwise. Worked fine previously with leaflet until I changed over to Google Maps.

**Comment by tmcw** [comment]
Hey,

Thanks for noticing this! I think it's an upstream regression in the Google Maps API and have filed a bug here: http://code.google.com/p/gmaps-api-issues/issues/detail?id=3752&thanks=3752&ts=1321812043

**Comment by underbluewaters** [comment]
Thanks for taking a look. Same assessment here, it would be a bit of a mess to try and work around this without some apis or changes made available on google's end.

**Comment by tmcw** [comment]
Google is unresponsive; closing.
