### ISSUE TITLE
Pass options to the Legend object to limit/specify a legend used.

### ISSUE THREAD

**Issue by tristen** [cutting-room-floor/wax#136]
For a few projects now we have had to come up with ways to not show a legend to avoid duplication of information or stacking. 

It would be nice to pass in options to the legend object specifying whether one legend should trump another or whether to show the top most layer's legend and not others.

**Comment by tmcw** [comment]
Out of scope for Wax - this is either in the hands of MapBox Hosting or individual sites.

**Comment by tristen** [comment]
Going to close. This is more of a server request issue.
