### ISSUE TITLE
Support multiple layers of interactivity for Leaflet

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/wax#138]
Kind of annoying, but it makes a lot of sense to do it.

**Comment by vidriloco** [comment]
Is there any guidelines on how to achieve this functionality?. I need to draw polylines and circles on a map, but obviously it's impossible because of the lack of multilayer support.

**Comment by tmcw** [comment]
@vidriloco that sounds like an other issue; are you talking about Modest Maps or something?
