### ISSUE TITLE
location interaction

### ISSUE THREAD

**Issue by calvinmetcalf** [cutting-room-floor/wax#140]
I'm trying to make a map of the municipal planning organization in Massachusetts so when you click on the shape, you go to the mpo website.  Try as I might I can't get it to work, the [documentation](http://mapbox.com/wax/interaction-mm.html) seems to suggest that simply putting a url in the location field of my mbtiles and then including the interaction connector should do the trick, but that isn't working for me.   I feel like I'm missing something here. 

you can view the map at [osm.no.de/mpo.html](http://osm.no.de/mpo.html)

**Comment by tmcw** [comment]
Hey Calvin,

Yep, that should do the trick, but a bug has been floating around in TileMill over the last week that doesn't export the location field correctly. If you're using a development copy of TileMill, update to the latest master. There'll be an OSX update in the next day or two, as well as an Ubuntu release. Sorry about that!

**Comment by calvinmetcalf** [comment]
closed the issue as it's really a tilemill one, thank you for the help, btw updated tilemill and it worked like a charm http://osm.no.de/mpo/
