### ISSUE TITLE
WMS and Modest Maps+Wax?

### ISSUE THREAD

**Issue by jhpoosthoek** [cutting-room-floor/wax#147]
Hi,

Is it possible to use ModestMaps+Wax and WMS?

Cheers, Jelmer

**Comment by kkaefer** [comment]
There are no plans to support WMS. [Leaflet](http://leaflet.cloudmade.com/) recently gained WMS support, though.

**Comment by jhpoosthoek** [comment]
Ah okay, I will check out Leaflet then!

**Comment by jhpoosthoek** [comment]
One other question, is it possible to use Modest Maps and Leaflet within one map DIV using Wax? There are a couple of Modest Maps features (like the autozoompan) I like and I need WMS too.

Another option would be to make a translation in PHP from X/Y/Z to WMS... I guess http://tilecache.org/ would so the trick ;)

**Comment by tmcw** [comment]
@jhpoosthoek is your WMS in EPSG:900913 (spherical mercator)? Though there's no official WMS support in Modest Maps, and the protocol scares me to death, it's probably pretty quick to whip up a simple WMS connector.

**Comment by jhpoosthoek** [comment]
No the WMS is WGS84, so I guess the WMS first has to be in spherical mercator yes...

Anyway, I'm just experimenting here, too see what is possible. Thanks for your comments.

**Comment by kkaefer** [comment]
Heads up, Leaflet might not support projections other than 900913/EPSG:3857 either, but I can't tell you that for sure.

**Comment by jhpoosthoek** [comment]
I will find out :D

I just like Wax and need to work with WMS so am trying to combine.
Installing tilecache.org is something I'm considering.

2011/12/14 Konstantin Kfer <
reply@reply.github.com
