### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by underbluewaters** [cutting-room-floor/wax#155]
I'm not sure if I'm just being dumb or something. I get this when trying to build wax when following the readme:

```
npm http GET https://registry.npmjs.org/banner
npm http 304 https://registry.npmjs.org/banner
npm http GET https://registry.npmjs.org/expresso
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/docco
npm http 304 https://registry.npmjs.org/docco
npm ERR! error installing banner@0.0.4
npm ERR! Error: No compatible version found: docco@'=0.3.0-'
npm ERR! Valid install targets:
npm ERR! ["0.2.0","0.3.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/local/lib/node_modules/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache.js:415:44)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:408:5
npm ERR!     at Object.saved [as oncomplete] (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--dev"
npm ERR! cwd /Users/cburt/Working/wax
npm ERR! node -v v0.6.6
npm ERR! npm -v 1.1.0-beta-7
npm ERR! message No compatible version found: docco@'=0.3.0-'
npm ERR! message Valid install targets:
npm ERR! message ["0.2.0","0.3.0"]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/cburt/Working/wax/npm-debug.log
npm not ok
```

**Comment by springmeyer** [comment]
Docco is not super critical to the dev environment. It looks like its not been updated in the while http://search.npmjs.org/#/docco and npm is basically saying that your node version will not likely work with it.

We're generally still running node 0.4.x, and node 0.4 works fine locally to run the build command for me. node 0.6.x is basically the same except for a refactor of core to support windows, so using node 0.4.x on your end should be fine.

**Comment by tmcw** [comment]
Good call: I abandoned the docco approach a while ago and forgot to remove it from package.json. It's now removed in master.

**Comment by underbluewaters** [comment]
Thanks for the quick help guys. 

btw, just finished a meeting with decisionmakers about choosing tools for marine data visualization in California. Our non-techie audience was just as excited as I am about using your stack after seeing how intuitively some complex habitat data could be presented.
