### ISSUE TITLE
mm.min.js: Uncaught abstract method not implemented by subclass

### ISSUE THREAD

**Issue by gabrielflorit** [cutting-room-floor/wax#158]
The latest modestmaps.min.js bundled here throws the following error (I'm trying to get the layer switcher TileMill demo to run):

Uncaught Abstract method not implemented by subclass. modestmaps.min.js:14

**Comment by tmcw** [comment]
Indeed, it needs an update - wax master is written against an untagged modest maps master. I'll hopefully get to this later.

**Comment by pdxmele** [comment]
Hi Wax team,

As a new user of MapBox I'd really like to try out Wax... could you make a version easily available that _does_ still work with MB, to hold us new users over until you get around to fixing the problem? Otherwise, any hints for a workaround are appreciated. Thanks.

**Comment by tmcw** [comment]
@saxbarm Wax team ~= me, and I'm a bit busy, but will hopefully get to this this afternoon.

**Comment by pdxmele** [comment]
Excellent, thank you!

**Comment by tmcw** [comment]
Okay: use Wax 5.0.1 and Modest Maps 1.0.0-alpha2 and you should be good to go, without having to wrap `wax.mm.connector` in a `MM.Layer`. So, like

```
    wax.tilejson('http://b.tiles.mapbox.com/awidercircle/1.0.0/awidercircle.AWC_street02,awidercircle.awc_don_rec_zip06/layer.json', function(tilejson) {
      map = new MM.Map('map', new wax.mm.connector(tilejson));
})
```

If you can confirm this as working I'm going to start updating the http://mapbox.com/wax site.

**Comment by pdxmele** [comment]
I wasn't sure where to put that code exactly (as I was just trying to get the sample from http://mapbox.com/wax/#making-your-first-map up and running to start off), but actually it looks like that original code is working just great now -- I'm no longer getting the exception. Thanks again!

**Comment by pdxmele** [comment]
I've moved on to the layerswitcher demo and everything is working fine--- except for the layer switching, of course. Now I get the error "m.setProvider is not a function" from within the refreshMap function.

**Comment by tmcw** [comment]
@saxbarm You can replace setProvider with `setLayerAt(0, layer)`, and it should work with the latest code.

**Comment by tmcw** [comment]
This is fixed in Wax and documented in the modest maps docs: https://github.com/modestmaps/modestmaps-js/wiki/Upgrading-to-1.0.0
