### ISSUE TITLE
Map doesn't scroll on iPad 1 (haven't tested iPad 2 yet)

### ISSUE THREAD

**Issue by setvik** [cutting-room-floor/wax#168]
We're developing a site with modestmaps and wax. I'm unable to pan the map with my finger on an ipad 1. We're using a very basic tilejson setup with .zoomer and .interaction 

See the map at the top of
http://mapbox.com/wax/
for an example. It does not pan either.

Is this a configuration issue / known bug?

**Comment by tmcw** [comment]
Hey,

What version of Modest Maps are you using? Pre 1.x, you'll need to add a specific array of handlers to the map, like `[new MM.MouseHandler(), new MM.TouchHandler()]`, in order to get touch events working.

**Comment by setvik** [comment]
That did it. I upgraded to the latest wax and it works on the ipad now. Thanks so much for the help!
