### ISSUE TITLE
Reacting to layers attributes

### ISSUE THREAD

**Issue by pmarkun** [cutting-room-floor/wax#170]
Hey all,

I don't even know if this is the right place to ask this (still trying to figure what is the boundaries of tilemill/wax/modestmaps).

What I want to do is a map where you can add some pins (just like in a RISK game?) and that the map reacts according to how many pins there are in a specific country (for example).

I can accomplish this by both creating another GeoJSON, KML and loading it externally.
Or I can do it by using the templates and storing the value on a hidden div (and then reading from it with javascript).

But those seems a little bit clumsy. Since I do have the information I need (which country, 'maximun pins numbers', etc) on the tilemill authored mtiles. It doesn't make much sense for me to replicate this elsewhare so when I click I can be aware of which shape I'm clicking on...

Is there a smarter way of doing it?

(Sorry if sounds confusing. Not good enought english and not good enought knowledge on how the system works to explain properly. And again, sorry if this is now the right place to ask!)

**Comment by tmcw** [comment]
Hey,

Yes, this will be possible in v6, but is a bit hard to do with UTFGrid and Wax right now. Stay tuned.

**Comment by pmarkun** [comment]
Awesome! I'll be waiting :)

(and betatesting when the time comes)

[]'s
Pedro Markun

On Tue, Feb 28, 2012 at 2:39 PM, Tom MacWright <
reply@reply.github.com

**Comment by tmcw** [comment]
The v6 api allows for part of this - reacting to interaction with the map in arbitrary ways. As far as the other part - making programmatic interaction with the map, closing in favor of #156.
