### ISSUE TITLE
Possible to use interaction without getting tile images?

### ISSUE THREAD

**Issue by JonnyBGod** [cutting-room-floor/wax#171]
Hi,

I am using wax with google maps and my idea is if it is possible to use wax to get the grid.json layer for interaction without the image layer.

My point would be to only use google maps images and grid.json.
At the moment I am using google maps layer + tms (.png) layer + grid.json layer.

For server simplification and cost reduction at least during the stating stages of my project it would be convenient to live without the extra non essential layer.

**Comment by tmcw** [comment]
Hey Jonny,

Currently not, and it'd be difficult to implement; Wax bootstraps its grid.json finding process by using PNGs on the map. Matthew Perry's [OpenLayers version](https://github.com/perrygeo/openlayers/tree/utfgrid) is written in a different way, so you'd be able to use interaction without tile images there, if you want to switch to OpenLayers.

Tom
