### ISSUE TITLE
Wax + Leaflet + IOS: Double-tap to zoom also triggered click event in Wax (solved)

### ISSUE THREAD

**Issue by fredleefarr** [cutting-room-floor/wax#173]
I was just testing wax on my iPhone and noticed that double-tapping over a utfGrid clickable area triggered both a zoom and my click handler at the same time. Drilling down into this I found that in Wax, the onUp() handler uses the following to remove listeners:

if (_container.ontouchend) {
            removeListener(_container, 'touchend', onUp);
            removeListener(_container, 'touchmove', _touchCancel);
}

On my iphone, the "_container.ontouchend" variable was always null, so the onUp listeners were never removed, so when double-tapping even though killTimeout() was called the click event was still triggered. I resolved this by replacing the above code with:

if(e.type === 'touchend') {
            removeListener(_container, 'touchend', onUp);
            removeListener(_container, 'touchmove', touchCancel);
           }

and this seems to have fixed the issue (tested on IOS & Chrome desktop).

Leaflet: 0.3.1
Wax: wax.leaf.js 5.0.0-alpha2
OS: IOS 5 on iPhone

**Comment by tmcw** [comment]
This was fixed after 5.0.0 - the code now uses code similar to what you're using.
