### ISSUE TITLE
minzoom, maxzoom broken with mm v1.0.0-alpha

### ISSUE THREAD

**Issue by sk1p** [cutting-room-floor/wax#175]
From a quick look, latest mm doesn't use outerLimits, as used in the connector, anymore.

Quick workaround: call setZoomRange on the Map instance

**Comment by tmcw** [comment]
Modest Maps enforces zoom ranges on layers by not serving tiles out-of-zoom - but yeah - the documentation needs to change to talk about how MM now handles zoom levels.

**Comment by sk1p** [comment]
This also affects wax.mm.zoomer: without setting the zoom range on the Map instance, wax.mm.zoomer does not disable the zoom in / zoom out buttons when the min/max is reached

**Comment by tmcw** [comment]
Updated the docs: http://mapbox.com/wax/connector-mm.html

`wax.mm.zoomer` should behave as it does now; it shouldn't look disabled if you can still use the control to zoom in & out of the map.
