### ISSUE TITLE
Create framerate-like test for performance of libraries

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/wax#18]

**Comment by gundersen** [comment]
@tmcw how much would this cost? What does this look like? 

![](https://img.skitch.com/20110615-rs33x4qqit5u4rn19b6mjb1jid.jpg)

**Comment by tmcw** [comment]
For 'the real thing' this could be quite difficult to do. I'm going to start reading up on possible methods to determine framerate like [getanimationframe](http://www.instapaper.com/text?u=http%3A%2F%2Fwebstuff.nfshost.com%2Fanim-timing%2FOverview.html), and start out with super-simple tests, like requestmanager unit tests or a simple zoom & to-completion test in modestmaps and openlayers.

**Comment by gundersen** [comment]
@tmcw @springmeyer, just wanted to post back on the framerate-like tests, I know Tom rocked some new Modest Maps work, would love to just keep pushing on speed here. Thoughts? Or is this just hard and something we don't want to fuck with till we get it right?

**Comment by tmcw** [comment]
In testing the transforms-refactor branch, I've finally gotten some in-browser perf testing working with [jslitmus](http://www.broofa.com/Tools/JSLitmus/). Right now it's just comparing the branches (making sure that mine's faster, mainly), but I'm going to do some tests with MM vs OpenLayers vs Google Maps on basic operations next.

**Comment by gundersen** [comment]
@tmcw awesome! Keep me posted how this plays.

**Comment by tmcw** [comment]
... this should use https://github.com/mrdoob/stats.js - just noting that for now.

**Comment by tmcw** [comment]
Out of scope for this project, chopping. This'll find a home in modestmaps, or a different project.
