### ISSUE TITLE
Highlight geometries

### ISSUE THREAD

**Issue by fmassot** [cutting-room-floor/wax#184]
Hi,

I was wondering if an interaction such as highlighting a geometry has been investigated in wax. It could be really cool to have something like this. I was thinking of the possibility to use grids to make it. 
Thx.

**Comment by tmcw** [comment]
Hey,

The glower project tries to address that - https://github.com/mapbox/glower

**Comment by fmassot** [comment]
Nice try indeed : ) 
The highlighting seems yet to be not very stable, am I wrong ? Are you considering other ways to achieve the same goal ?
