### ISSUE TITLE
Create embed embedder for Modest Maps

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/wax#19]

**Comment by dhcole** [comment]
Two things on this:
- What would it take to build and how does this rank with other priorities? We're using this a lot on microsites now, so it would be more efficient to get it upstream.
- Can we make it (optionally) reflect the current state of the map (zoom, center point, and layers)?

**Comment by tmcw** [comment]
This should go in a wax-ext library, not in Wax. Closing this for now - let's start up a collection soon.
