### ISSUE TITLE
interaction.remove() has undefined variables

### ISSUE THREAD

**Issue by dhcole** [cutting-room-floor/wax#193]
`clearingEvents` and `clearTileGrid` are undefined and cause an error.
https://github.com/mapbox/wax/blob/master/dist/wax.mm.js#L2427-2428

**Comment by tmcw** [comment]
Actual file is https://github.com/mapbox/wax/blob/master/control/lib/interaction.js#L183

Plz reference source files rather than built files when possible.

**Comment by springmeyer** [comment]
could this be the cause of https://github.com/mapbox/tilemill/issues/1423 ?

**Comment by tmcw** [comment]
Fixed in 6bd6ee600a6dc5232be02f3fe84f9a55de5e266b
