### ISSUE TITLE
Control opacity of the layer in wax for google maps

### ISSUE THREAD

**Issue by xavijam** [cutting-room-floor/wax#194]
Something I just miss, not sure if it is possible to implement.
Thanks for your effort!

**Comment by dooley** [comment]
Yes, that is what i need too currently. Or someone found a solution already?

**Comment by tmcw** [comment]
Is this implemented anywhere else? I'm not sure whether this really makes sense in Wax.

**Comment by dooley** [comment]
Easy solution, as long as the custom attribute 'gTileKey' is set in wax, is to use that attribute as CSS selector:

<style>
  img[gTileKey] {
    opacity: 0.5;
    filter: alpha(opacity=50);
  }
</style>


From my side this can be closed.

Regards, dooley

**Comment by xavijam** [comment]
Yep, close this ticket, I'll do a pull request if you find it interesting. Thanks @dooley!
