### ISSUE TITLE
make command failed with bing error

### ISSUE THREAD

**Issue by fmassot** [cutting-room-floor/wax#195]
Hi there,
Just to let you know that make command outputs the following error:

```
cat: connectors/bing/*.js: No such file or directory
make: *** [dist/wax.bing.min.js] Error 1
```

Maybe you plan to add bing files very soon : )

François

**Comment by tmcw** [comment]
Removed in f115c6e2652890b29a7f69aa688b732cc32c3f0b

This will eventually have bing support, but I'm not very keen on it; the Bing API is closed and the terms of service are aggressive. Kind of the situation of integrating with an unwilling party.

**Comment by fmassot** [comment]
Thx
