### ISSUE TITLE
Dismissing a tooltip triggers a click event on an interactive layer

### ISSUE THREAD

**Issue by willwhite** [cutting-room-floor/wax#203]
I think we've fixed this problem before, but it's regressed.

Example map: https://tiles.mapbox.com/energy/map/map-9vpuir90
1. Activate a tooltip
2. Position the map so that another interactive feature is below the tooltip's close button in z-space.
3. Click the close button--the tooltip will disappear but another tooltip will appear for the feature below the close button.

**Comment by tmcw** [comment]
The fix is already in place for this: https://github.com/mapbox/wax/blob/master/control/lib/tooltip.js#L82
And has been for a while; this might be another issue specific to MapBox Hosting.
