### ISSUE TITLE
IE and multiple leaflet maps on a single page

### ISSUE THREAD

**Issue by pimlinders** [cutting-room-floor/wax#205]
When adding multiple leaflet maps on one page I get the follow error

"SCRIPT5007: Unable to get value of the property '0': object is null or undefined 
wax.leaf.min.js, line 2 character 5398"

Problem occurs in IE7-9.  Issue has also been discussed here http://support.mapbox.com/discussions/general-questions/1369-more-than-one-waxleaflet-map-per-page

**Comment by tmcw** [comment]
Hi Pim,

I'll handle this at the original discussion: http://support.mapbox.com/discussions/general-questions/1369-more-than-one-waxleaflet-map-per-page
