### ISSUE TITLE
Update mustache

### ISSUE THREAD

**Issue by ansis** [cutting-room-floor/wax#213]
Current version has a formatting bug. Details here: http://support.mapbox.com/discussions/tilemill/869-possible-tilemill-bug-with-interactivity-and-json-objects

The bug has been fixed in mustache.

**Comment by tmcw** [comment]
There hasn't been a mustache release in 4 months, may have to use the dev version, unfortunately.

**Comment by ansis** [comment]
Its a fairly small bug with a simple workaround so it might not be that bad to wait.
