### ISSUE TITLE
reqwest undefined in 6.2.1 wax.leaf[.min].js

### ISSUE THREAD

**Issue by bobholt** [cutting-room-floor/wax#214]
Attempted to use v 6.2.1 with the following code, but received a "Uncaught ReferenceError: reqwest is not defined" error on line 3049 of wax.leaf.js (error also occurs on wax.leaf.min.js). No errors in 6.2.0.

My code:

``` javascript
var mapUrl = "http://a.tiles.mapbox.com/v3/mymap.jsonp";

wax.tilejson(mapUrl, function(tilejson) {
  var map = new L.Map('mapbox').addLayer(new wax.leaf.connector(tilejson)).setView(new L.LatLng(0, 0), 3);
});
```

**Comment by tmcw** [comment]
Not seeing this issue: http://bl.ocks.org/2955262

**Comment by bobholt** [comment]
Interesting. Yes, that obviously works.

I'm using require.js 2.0.2 and loading leaflet and wax as modules, so
there may be some weirdness there. My implementation definitely breaks
on 6.2.1, but works on 6.2.0. If I get a chance, I'll create a fiddle
better replicating my setup.

On Tue, Jun 19, 2012 at 1:00 PM, Tom MacWright
reply@reply.github.com
wrote:

**Comment by tmcw** [comment]
Ah, yeah - we don't test or use require.js internally, so I don't quite know how it'll react to the new changes in reqwest.

**Comment by tmcw** [comment]
Looks like an incompatibility between reqwest and require.js that will be fixed upstream; we need the newer reqwest version here for IE compatibility so can't downgrade at this point.
