### ISSUE TITLE
Improve zoom control detection

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/wax#222]
Right now the zoom control is not properly showing that it's disabled.

**Comment by tmcw** [comment]
@aibram want to grab this one? basically resolving the intersection of wax.mm.zoomer to make it aware of new-style modest maps limits - might be a very quick task.

**Comment by ansis** [comment]
Fixed in 0a383d4cfe93ebe15fb1d93923e2b51f6dcf3cbd
