### ISSUE TITLE
reqwest is not defined

### ISSUE THREAD

**Issue by jenssegers** [cutting-room-floor/wax#227]
I am loading a html file with ajax that contains all the script tags for mapbox to work. The map is unable to render and I get "reqwest is not defined" in the console.

The same problem occurs when loading the required scripts with jquery $.getScript().

**Comment by tmcw** [comment]
are you using requireJS? is there a live example of this happening?

**Comment by jenssegers** [comment]
No I am not using requireJS. But I can imagine getScript and requireJS work in a similar way.

**Comment by tmcw** [comment]
This is a recent version of Wax? Latest?

**Comment by tmcw** [comment]
Assuming this is because of jQuery's getScript.
