### ISSUE TITLE
legend demos appear broken

### ISSUE THREAD

**Issue by springmeyer** [cutting-room-floor/wax#234]
Seen in chrome 20.0.1132.57

<img src="https://img.skitch.com/20120717-r2xnmkfj3s7wt7pbfjd8kyw7ag.jpg" />

**Comment by tmcw** [comment]
@tristen this might be style-revision related?

**Comment by tristen** [comment]
Ah should have closed this. Fixed in https://github.com/mapbox/wax/commit/2e53e0696c78678ad5777ff037b30ed53bb3b243
