### ISSUE TITLE
map-controls.png revision

### ISSUE THREAD

**Issue by tristen** [cutting-room-floor/wax#236]
Currently the map-controls.png looks like this: https://github.com/mapbox/wax/blob/a2b3f2bed8ca5e7cea87e007f9541084e9c2b1f7/theme/map-controls.png

I left the mapbox logo in there as I thought it may be necessary but I think we can cut this right?

This also raises a discussion made here in  mapbox/mapbox.js#14
If we provided a different retina scaled png (we should probably do this in a css media query) this leaves us with another theme dependency to users using mapbox.js. I think removing the mapbox logo from the sprite and optimizing the size of the sprite overall might allow us to base64 encode the png

thoughts @yhahn ?
cc @tmcw

**Comment by tristen** [comment]
FWIW this is what the blob looks like with mapbox removed:

```
iVBORw0KGgoAAAANSUhEUgAAAJYAAAAeCAYAAADO4udXAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHFSURBVHic7dpBbsIwEAXQoZpbwKKz8Bm66EFyjUicI1KuwUF6Ci/cBbmFJbqoLbluJezgMSn8JyGhJMRAvmZiw+5yuRBAay/3fgPwmBAsUIFggQoEC1QgWKACwQIVCBaoQLCgiIiMIjKWHo9gbVy4oJ/po9e42fPiUBERcemBxpiD935i5qO19ly6rzUR+SAics69a46zFc65WUSIKi9sA2MYN449O+fm0hcXVyzv/UREb977kzHmELeHUJ3Cvqn0fDfYhwfoi5WqKlREFRWLmY8hQPsQroGIKG4jooWZjzWDw3VJG4oXtnflWqU4WNbaszFmSMMVdsVQDdpt8NmkoYoVI2lPPY0iQjVVa1f774ak9cV2pBqqcE91rfUtre+57jGuiIxJgFa3oS0orljQxU03zGv8NeNzzr3eet6qipVVqyVs7toK43S7xYffmmwpoVulysPV4rstnhXmoWLmgZkH+g7YPp8twnOrXW74UZ2stecsXD2WG55F1Ur3Wtmss1mFrF1u+LUImswWp07LDcv1Q/6n3u1dc9ZZPSuExxErosa9HIIFKvAjNKhAsEAFggUqECxQgWCBCgQLVCBYoALBAhVfpi7sxwlEhWYAAAAASUVORK5CYII=
```

Its not that long! so we would have two of these in our css

**Comment by yhahn** [comment]
I'm down with this idea -- we can provide the mapbox logo for watermarking as a separate image on mapbox hosting.

**Comment by tmcw** [comment]
Note that IE7 doesn't support data-uris, but maybe this doesn't matter?

**Comment by tristen** [comment]
It doesn't but we can make a note of that in our docs and keep a copy of map-controls.png in the repo

**Comment by tristen** [comment]
Closing. Added!
