### ISSUE TITLE
Add layers to hash control

### ISSUE THREAD

**Issue by ansis** [cutting-room-floor/wax#240]
Would it be within the scope of Wax to (possibly optionally) add a list of enable layers to the hash, now that MM supports both named layers and enabling disabling layers?

**Comment by tmcw** [comment]
:/ maybe, though it seems like scope creep. if you want to do some research into combinable hashes (like indicating multiple states in a hash) go for it.

**Comment by ansis** [comment]
Yeah, this is scope creep and there is no nice way to listen for layer changes. More suitable as a mapbox.js extension.
