### ISSUE TITLE
Inverted sections in mustache are broken

### ISSUE THREAD

**Issue by willwhite** [cutting-room-floor/wax#241]
cd05aa280dba4beefa2884ca6f78eb433bc60dfc upgrades mustache to v0.5.0-dev, but inverted sections are broken in this version, resulting in empty tooltips. Since there still hasn't been a new tag for mustache, we need to see if it's fixed in master. If not, we need to hunt down the problem commit and work on a fix.

**Comment by tmcw** [comment]
Done in push.
