### ISSUE TITLE
No max-width on legends

### ISSUE THREAD

**Issue by ansis** [cutting-room-floor/wax#244]
Previous theme had a maximum width on legends, this one doesn't.

@tristen is this intentional?

**Comment by ansis** [comment]
Since this got deployed on mapbox hosting users are having issues with their legends displaying differently. Should `max-width` and `max-height` be re-added or should users update their legend styles?

@tristen

**Comment by tristen** [comment]
Can you shed a bit more light on this? Did the breakage come from tilestream? Not sure I'm seeing the line where I changed this.

**Comment by yhahn** [comment]
Looks like I removed this from ts pro when we made the switch assuming `mapbox.js` had inherited this work

https://github.com/developmentseed/tilestream-pro/commit/fa96971293ed59345a95674a0df5f56b90364edc

I think this should be part of default `controls.css` in mapbox.js especially as it will provide consistency with tilemill when tilemill goes mapbox.js as well.

**Comment by tristen** [comment]
Fixed upstream

**Comment by tristen** [comment]
committed the change here too: https://github.com/mapbox/wax/commit/d27039cff6f002cac690438b06fb0174c61a0356

@tmcw what's the schedule like for rolling this into a version of mapbox.js?

**Comment by tmcw** [comment]
Closing this, moving to mapbox/mapbox.js#114
