### ISSUE TITLE
Fullscreen via body class only?

### ISSUE THREAD

**Issue by yhahn** [cutting-room-floor/wax#245]
This may be fixed by https://github.com/mapbox/wax/commit/2ce3672e08ce7d4c17857350275cef4962d53500 but I'm not sure.

I've run into an issue where a map div's dimensions are initially defined using relative units (e.g. `width:50%`). Once it goes into fullscreen mode and back the control sets its parent's dimensions explicitly using absolute units (e.g. `493px`) based on the size of the window at the time meaning any further window resizes tend to break the intended layout of the page.

Is there any way the fullscreen control could work _without_ explicity setting the absolute sizes of the map container? ie. just adding/removing a body/container class with CSS rules for fullscreening the map?

**Comment by ansis** [comment]
Opened a pull at #246

**Comment by ansis** [comment]
Merged in a4cc6d65cd60fc923233bb77fa82c22e82c2bc0b
