### ISSUE TITLE
Remove interaction function problem in Gmapsv3

### ISSUE THREAD

**Issue by xavijam** [cutting-room-floor/wax#248]
I'm trying to remove the interaction in Google maps, but it's failing.
Here is one of your examples:

http://vizzuality.github.com/cartodb-gmapsv3/wax-bug.html

If you try in the console:

interaction.remove();

Fails and say:

TypeError: Object #<V> has no method 'remove'

PS: With Leaflet is working properly.

**Comment by wboykinm** [comment]
I see Javier caught exactly the same issue [I just stumbled on](http://dev.geosprocket.com/hon). using interaction.remove(); to push the next interactivity in a layer switcher results in the same `TypeError: Object # has no method 'remove'` error.

**Comment by wboykinm** [comment]
I see that Javier 7 (how do you guys not get confused over there? - @javisantana) may have solved it. [Here's his update](https://github.com/CartoDB/wax/commit/1838dc8590e2c7aecf45a261d9a79c56030433f9) to interaction.js. @tmcw or @willwhite - can either of you push this in tomorrow?

**Comment by javisantana** [comment]
@wboykinm hey, i didn't realize @xavijam was posted this bug. I found this some weeks ago, fixed it in out wax version and i forgot to send a pull request.

**Comment by willwhite** [comment]
Can you make a pull request with the fix?

**Comment by javisantana** [comment]
@willwhite sure, give a minute

**Comment by javisantana** [comment]
done https://github.com/mapbox/wax/pull/263
