### ISSUE TITLE
wax.leaf.js selecting wrong UTFgrid tile

### ISSUE THREAD

**Issue by infostreams** [cutting-room-floor/wax#257]
Hi guys,

I have a map with about 16.000 datapoints in them. When you mouse over one of those points, it shows you some information on that point.

However, I noticed something strange today - whenever I would zoom in to the deepest zoom level, the interactivity grid would start behaving strangely. At first, after having zoomed in, for the tile I was on, it would still function properly: move over a point and you would see the popup. However, if I would drag around a bit (let's say half a continent), and then move back to where I was, my mouseover would no longer work. Even stranger, it would show me popups (teasers) on places that should definitely not have a mouseover, like in the middle of the sea.

Anyway, long story short, it turns out (after a very frustrating 2 hour bug hunt) that in some cases, the wrong UTFgrid is selected. That UTFgrid is then used for determine the mouse overs, and since we're using the UTFgrid of another tile it messes up everything.

I eventually tracked it down to a bug in 'wax.u.offset()'. In the anonymous function 'calculateOffset()', the offset was calculated incorrectly. Basically, the 'top' offset was off by a few hundred pixels, which made it seem that a tile was in a different place than it actually was. And that in turn selected the wrong UTFgrid tile, which consequently broke the interactivity.

And all of this was caused by a incomplete regular expression.

Anyway, to fix it, change 

```
            if (match = style.match(/translate\((.+)px, (.+)px\)/)) {
                top += parseInt(match[2], 10);
                left += parseInt(match[1], 10);
            } else if (match = style.match(/translate3d\((.+)px, (.+)px, (.+)px\)/)) {
                top += parseInt(match[2], 10);
                left += parseInt(match[1], 10);
            } 
```

to 

```
            if (match = style.match(/translate\((.+)[px]?, (.+)[px]?\)/)) {
                top += parseInt(match[2], 10);
                left += parseInt(match[1], 10);
            } else if (match = style.match(/translate3d\((.+)[px]?, (.+)[px]?, (.+)[px]?\)/)) {
                top += parseInt(match[2], 10);
                left += parseInt(match[1], 10);
            } 
```

Basically, it makes the 'px' postfix optional. The leaflet code I run uses '-webkit-transform: translate3d(..px, ..px, 0)' in the .leaflet-map-pane div, and the current regular expression _doesn't match_ that style, and therefore doesn't take those values into account, and then as a result breaks the interactivity layer.

You could argue that this is a bug in Leaflet, but I think that Wax should support even half-broken CSS like the one I described. It might even be legal CSS (didn't look at the specs).

Anyway, in order to prevent other people from some serious head scratching, I would appreciate it if you could include this fix in your next release. Thanks!

**Comment by javisantana** [comment]
related: https://github.com/mapbox/wax/issues/242

cc @tmcw

**Comment by tmcw** [comment]
Related pull request merged, will rebuild...

**Comment by infostreams** [comment]
This is not the same bug as #242, and it is not fixed in  https://github.com/mapbox/wax/commit/6b1c56c589087e623056216ec54a1e3498829a89

It is in the same piece of code, but it is a distinctly different bug. You can even clearly see why it isn't working: if the style is -webkit-transform: translate3d(500px, 430px, 0) and the regexp is /translate3d((.+)px, (.+)px, (.+)px)/ then it will NOT match that statement and it will miscalculate the location by 500px and 430px respectively.

**Comment by tmcw** [comment]
Reopening then. Can you make a pull request for your fix, @infostreams ?

**Comment by kunal456** [comment]
Thanks
It works for me perfectly
