### ISSUE TITLE
interaction does not work in IE10 (+ patch)

### ISSUE THREAD

**Issue by javisantana** [cutting-room-floor/wax#271]
hey guys, interaction is not working on IE10 due a bug in reqwest with jsonp, this is the patch for IE10

https://github.com/CartoDB/reqwest/commit/fb81953f348e069604145dac90284a134763ce1d

hope it helps

**Comment by yhahn** [comment]
Thanks javi -- this is part of the wax `7.0.0-dev13` tag now.
