### ISSUE TITLE
Embeds do not work in FF 3.x

### ISSUE THREAD

**Issue by springmeyer** [cutting-room-floor/wax#42]
No map appears at http://developmentseed.org/blog/2011/may/16/tilemill-020-release in Firefox 3.6.16.

<img src="https://img.skitch.com/20110516-8179w51ftpx8h912fse3wgce5a.jpg" />

**Comment by tmcw** [comment]
Currently I'm not seeing the element get created, or anything like that. [This is the embedded iframe](http://dl.dropbox.com/u/342088/geoclass-embed.html), and it doesn't produce any errors either. I'm saying hold off on this until TileStream's embeds are updated to MM/noQuery.

**Comment by yhahn** [comment]
Taking a look at the source file for this iframe at http://dl.dropbox.com/u/342088/geoclass-embed.html it looks like the issue is that there is no `<head></head>` tag which the embeds need to dynamically add scripts, styles, etc.

Going from this code

```
<div id='ts-embed-1305557235495-script'><script src='http://tiles.mapbox.com/mapbox/api/v1/embed.js?api=ol&size%5B%5D=500&size%5B%5D=300&center%5B%5D=3.9550781249252&center%5B%5D=19.890723023403&center%5B%5D=1&layers%5B%5D=geography-class&options%5B%5D=legend&options%5B%5D=zoompan&options%5B%5D=tooltips&options%5B%5D=zoomwheel&el=ts-embed-1305557235495'></script></div>
```

to this code

```
 <html><head></head><body>
 <div id='ts-embed-1305557235495-script'><script src='http://tiles.mapbox.com/mapbox/api/v1/embed.js?api=ol&size%5B%5D=500&size%5B%5D=300&center%5B%5D=3.9550781249252&center%5B%5D=19.890723023403&center%5B%5D=1&layers%5B%5D=geography-class&options%5B%5D=legend&options%5B%5D=zoompan&options%5B%5D=tooltips&options%5B%5D=zoomwheel&el=ts-embed-1305557235495'></script></div>
</body></html>
```

works for me.

**Comment by yhahn** [comment]
Discussed with @willwhite and removed iframe. Embed should work (may not be updated right away... Drupal page cache ;)
