### ISSUE TITLE
Don't try to redownload grid.json after status >= 400

### ISSUE THREAD

**Issue by kkaefer** [cutting-room-floor/wax#49]
Currently, wax tries to redownload a grid.json file on every mouse movement when the previous download failed due to a 404. We should either send a 200 response with a reasonable default or stop wax from attempting to redownload failed grid.json files.

**Comment by springmeyer** [comment]
+1

**Comment by tmcw** [comment]
Fixed by 0cb32537ea87a7c210bf5328d9c5efd0c9afbbf9
