### ISSUE TITLE
interaction broken?

### ISSUE THREAD

**Issue by sk1p** [cutting-room-floor/wax#50]
Hi,
the interaction example in the manual ( http://mapbox.github.com/wax/manual/index.html ) seems to be currently broken. It only works as long as you don't pan/zoom. Then, when moving the mouse over the map, it throws

```
Uncaught TypeError: Cannot call method 'charCodeAt' of undefined
```

at wax.mm.js:287 (in wax.GridInstance.getFeature)

At one instance, this was because (y-tileY) was negative, though I have no idea how this can happen...

**Comment by yhahn** [comment]
Yep, I have seen this as well... will have to do some more sleuthing.

**Comment by tmcw** [comment]
This should be fixed now - update if it's still happening.
