### ISSUE TITLE
Rogue tiles in tilegrid cache

### ISSUE THREAD

**Issue by yhahn** [cutting-room-floor/wax#53]
Just committed https://github.com/mapbox/wax/commit/1e44e80deb5e5ca4dc785b55878526e5f558376a - looks like some renaming didn't propogate through or so. Interaction on MM is working but once in a while there is a hard to reproduce behavior where the wrong feature data will be pulled when hovering over a given area.

My guess is that there is some race condition or leak in how the cache is generated, leaving a bad tile/offset object in the cache that is getting iterated over and catching the event coordinates before it hits the actual correct tile.

**Comment by springmeyer** [comment]
is this related to #50 (which I see encounter frequently)?

**Comment by tmcw** [comment]
This one's fixed a while ago.
