### ISSUE TITLE
allow tileRes to be configurable to test 128 and 256 size grids

### ISSUE THREAD

**Issue by springmeyer** [cutting-room-floor/wax#54]
I'm seeing that for lots of equally small sized points that 64/64 may not be sufficient and the resampling causes points to be lost. To test this hunch I'd like to load 128 and 256 (full res) grids using Wax. But changing [line 57 of gridutil.js](https://github.com/mapbox/wax/blob/master/control/lib/gridutil.js#L57) (in the built ol.wax.js on line 254) to `2` does work as expected. Grids do not display and I get an error like:

```
wax.ol.js:284: TypeError: Result of expression 'this.grid_tile.grid[
     Math.floor((y - tileY) / this.tileRes)
  ]' [undefined] is not an object.
```

Any idea what I might be doing wrong?

**Comment by springmeyer** [comment]
in further testing 64/64 actually looks fine in the case I was looking to test 128. But, in the future it still may be useful to be able to use 128 for greater accuracy, so any thoughts on what might be going wrong here would be great.

**Comment by tmcw** [comment]
resolution is now configurable through the OpenLayers control, and I'm not seeing this come up. However, it still needs to be configurable through the rest of the controls, so keeping this issue open.

**Comment by tmcw** [comment]
Fixed to the level that we can, re-circle around this one if we start seeing / using different resolutions.

**Comment by springmeyer** [comment]
great, ya, should have closed this at the time, thanks!
