### ISSUE TITLE
handling grids without 'data' property

### ISSUE THREAD

**Issue by springmeyer** [cutting-room-floor/wax#55]
The utfgrid spec says explicitly that the 'data' property is optional: https://github.com/mapbox/mbtiles-spec/blob/master/1.1/utfgrid.md

But wax currently will fail in gridutil when attempting to format based on empty data: https://github.com/mapbox/wax/blob/master/control/lib/gridutil.js#L187 and will console.log():

```
TypeError: Result of expression 'data' [undefined] is not an object.
```

The deeper question is likely how to allow users of the wax library to add hooks to control what 'data' is show for a given key. For example a potential need others might have would be to fire off an http request for a given value.

In the near term I propose simply displaying the key in the wax tooltip. This enables a simple usecase where a formatter is uneeded and the actual key is the data that might be desired to be show, and it is kinder to new users that might be setting up wax (vs. catching the exception within wax).

**Comment by springmeyer** [comment]
added the behavior I'd like to see - @tmcw please correct/advise.

**Comment by tmcw** [comment]
Changed this behavior - grids without data will not cause errors, but will also not failback to the key - a formatter with the key as its only output is more consistent and predictable.
