### ISSUE TITLE
Disable zooming while scrolling

### ISSUE THREAD

**Issue by kkaefer** [cutting-room-floor/wax#63]
See http://cl.ly/0J2Q0D2K1D2r2A101O1k

We should disable zooming when the last mouse action was scrolling. As soon as the user moves, we should zoom in/out on the map. This is in addition to completely disabling scrollwheel zooming.

**Comment by tmcw** [comment]
Hmm, interesting, so yeah, I guess this would live in wax itself, though it's in kind of a nether region between the two.

It would involve stopping scroll events if there's no mousemove after the mouse enters the map?

**Comment by kkaefer** [comment]
Yeah, this could potentially be a very simple algorithm and live completely in wax: disable zooming by default, and register these events:
- mouseenter: set zoomable to false
- mousemove: set zoomable to true

**Comment by tmcw** [comment]
Doesn't belong in Wax. Moving to [deadsea](https://github.com/tmcw/deadsea).
