### ISSUE TITLE
Option to stop clicks from passing through popups

### ISSUE THREAD

**Issue by ajashton** [cutting-room-floor/wax#65]

**Comment by perrygeo** [comment]
Is there any word on this issue? Any workarounds?

**Comment by tmcw** [comment]
Okay, so the strict branch contains some more intense checking that the click target is properly a map tile instead of a popup or whatnot - and does the same thing for hover events. I'm not sure that this will be regression-free so try it out on projects first to kick the tires.

**Comment by tmcw** [comment]
Strict branch merged. More to do to check that this is working, but closing: this'll be in the next tag.
