### ISSUE TITLE
Add TileJSON docs, improve documentation in other areas

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/wax#74]
The tilejson documentation is more or less hastily added, without enough context to guide users on what exactly it's doing. I think there are a few other controls of this type, where we should really build out docs more.

It would also be useful adding documentation on updating to 3.0.0 and explaining some of the design decisions for why the API changed.

**Comment by yhahn** [comment]
I've given this an overhaul and added some changelog entries for 3.x ... @tmcw maybe you have something more detailed in mind for upgrade notes?

**Comment by tmcw** [comment]
Good enough for now - I'm planning on doing a more extensive sweep soon.
