### ISSUE TITLE
Browser testing

### ISSUE THREAD

**Issue by yhahn** [cutting-room-floor/wax#77]
The usual.

**Comment by yhahn** [comment]
Looking good in IE, Firefox.

@tmcw which mobile browsers do we need to hit?

**Comment by tmcw** [comment]
iPad & Galaxy Tab. @ericg and @tristen are into Blackberry support but from what I've seen the developer toolkit is painful.

**Comment by yhahn** [comment]
We're good enough I think... no catastrophic fails.
