### ISSUE TITLE
min version info

### ISSUE THREAD

**Issue by tristen** [cutting-room-floor/wax#79]
It would be nice for say, `wax.mm.min.js` to have a version number.

Currently the file starts like this:

> /*!
> - Reqwest! A x-browser general purpose XHR connection manager
> - copyright Dustin Diaz 2011
> - https://github.com/ded/reqwest
> - license MIT

Which is already confusing as it starts with its library dependency.

**Comment by tmcw** [comment]
Fixed back in 65a06205ac6145ee109be665605c39a99a7e94c0
