### ISSUE TITLE
Interaction control caches deep

### ISSUE THREAD

**Issue by yhahn** [cutting-room-floor/wax#80]
Here's the use case -- someone's editing a project in TileMill and updates the `formatter` and/or `grids` URL of tilejson. It's more or less impossible atm to get the interaction control to update its `formatter` or its grids URL template without nuking the existing map and creating a new one.

Possible solution - expose the wax gridManager publicly so it can be replaced on updates?

**Comment by tmcw** [comment]
Yeah, I think so. Either have like an `interaction.g.formatter()` or proxy all of the methods.

**Comment by tmcw** [comment]
You can now call `interaction.tilejson(tilejson)` with a new object and it will set templates, formatters, and grid URLs to new locations and code.
