### ISSUE TITLE
Boxselector public API

### ISSUE THREAD

**Issue by yhahn** [cutting-room-floor/wax#81]
Another TileMill use case -- the coordinates of the boxselector div need to be manipulated via API rather than just the mouseUp/mouseDown events.

**Comment by willwhite** [comment]
@tmcw it would be cool to get this into TileMill 0.5.1. What's your sense on how hard this would be?

**Comment by tmcw** [comment]
Added to gh-pages in fc170c5b9d885d50d9a8efa9a2d3542e8868ae14
