### ISSUE TITLE
Location clickAction doesn't fire consistently

### ISSUE THREAD

**Issue by dhcole** [cutting-room-floor/wax#83]
Custom clickAction functions triggered by clicking on features with a location formatter are not consistently being called. See this example: https://gist.github.com/a8a74a90ad7c9a895a01

Often it takes several clicks to get a console.log message. Sometimes, this happens after the first click though.

This may be related to https://github.com/mapbox/wax/issues/67.

**Comment by tmcw** [comment]
Fixed in 60c34575206bd881e06c159f2ecfedaad1c8baaf
