### ISSUE TITLE
Click callback not receiving event object

### ISSUE THREAD

**Issue by nateirwin** [cutting-room-floor/wax#86]
I'm using wax.mm.interaction to add interaction to a TileStream layer. I am overwriting the default out, over, and click interactions with own callbacks. Everything is working fine, but the event object that should be passed into the click callback is always undefined.

I've traced the problem back to the onUp function:

```
// Contain the event data in a closure.
_clickTimeout = window.setTimeout((function(pos) {
    return function(e) {
        console.log(e); // This is undefined

        _clickTimeout = null;
        click(e, pos);
    };
})(pos), 300);
```

**Comment by tmcw** [comment]
and `pos` is undefined as well? The mouseup event isn't going to be informative, so I'm trying to save the mousedown/click data for the callback.

**Comment by nateirwin** [comment]
Nope, <code>pos</code> is passed to the <code>click</code> function properly. I don't understand how you are planning to preserve the mousedown/click event object, as AFAICT it is never passed into the <code>onUp</code> function.

An obvious simplified version is:

```
_clickTimeout = window.setTimeout(function() {
    _clickTimeout = null;
    click(e, pos);
}, 300);
```

But maybe I'm missing something here?
