### ISSUE TITLE
Um, link to Wax from the manual

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/wax#87]
This was lost in updates and redesigns.

**Comment by yhahn** [comment]
http://mapbox.github.com/wax/manual/index.html#downloads

**Comment by tmcw** [comment]
Not to nitpick, but can we link to the main GitHub page too? Open source projects that push tarballs are kinda weird.

**Comment by yhahn** [comment]
https://github.com/mapbox/wax/commit/1979c47baa6deb46e655d2de504c55c0af4d71c4

feel free to tweak
