### ISSUE TITLE
Embed support as a wax control

### ISSUE THREAD

**Issue by tristen** [cutting-room-floor/wax#92]
It would be nice if wax provided embed functionality. Currently this has been implemented manually in projects. An example of such an implementation is here: https://gist.github.com/1128745

The flexibility of being able to revise the embed code if a user were to toggle on different layers and select the type of map they wish to embed would be key here. That might sound more project specific but I assume this could happen automatically if say `wax.mm.embed` were passed through the tilejson object.

**Comment by tmcw** [comment]
Duplicate of #19

**Comment by tristen** [comment]
o nice
